apiVersion: v1
kind: PersistentVolume
metadata:
  name: microclimate-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  nfs:
    path: /storage/mc-jenkins
    server: 10.40.41.160