apiVersion: v1
kind: PersistentVolume
metadata:
  name: microclimate-workspace
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  nfs:
    path: /storage/mc-workspace
    server: 10.40.41.160